// action type
export const GET_VOYAGEORGANISES = "GET_VoyageOrganises";
export const DELETE_VOYAGEORGANISE = "DELETE_VOYAGEORGANISE";
export const ADD_VOYAGEORGANISE = "ADD_VOYAGEORGANISE";
export const GET_SINGLE_VOYAGEORGANISE = "GET_SINGLE_VOYAGEORGANISE";
export const UPDATE_VOYAGEORGANISE = "UPDATE_VOYAGEORGANISE";
export const GET_MOYENDETRANSPORTS = "GET_MOYENDETRANSPORTS";
export const GET_HOTELS = "GET_HOTELS";
export const GET_ORGANISATEURS = "GET_ORGANISATEURS";